[package]
name = "future"
version = "0.1.0"
authors = ["dengjie <jie.deng@17zuoye.com>"]
edition = "2018"

[dependencies]
serde = "1.0.80"
serde_json = "1.0.33"
mysql = "*"
tokio = "0.1.13"
lazy_static = "1.2.0"
serde_derive = "1.0.87"
csv = "1"
proc-macro2 = "0.4.27"
syn = "0.15"
quote = "0.6"
